### ISSUE TITLE
Implement rain sensor support

### ISSUE THREAD

**Issue by giovanifss** [giovanifss/Datacenter-Monitor#2]
Make Arduino recognize and collect data from rain sensor.

**Comment by giovanifss** [comment]
@gustavoorc Quando vc fizer o upload dos arquivos, marca o professor aqui pra ele ver a entrega. Pra marcar alguem eh so colocar '@' que ai vai aparecer o usuario dele.

**Comment by gustavoorc** [comment]
@eduardosan professor, os codigos referentes aos sensores de umidade, temperatura e chuva estao no repositorio.
