### ISSUE TITLE
Paper: Section 2 (Related Concepts) and Section 3 (Problem definiiton and Proposal)

### ISSUE THREAD

**Issue by giovanifss** [giovanifss/Datacenter-Monitor#5]
Both sections must be concluded in 16/05.

**Comment by giovanifss** [comment]
@eduardosan Tentei fazer o que vc falou e dar uma compactada nas coisas. Nao sei se o resultado ficou muito interessante nao, da uma avaliada ai. Adicionado no commit 5814d685d45064b4ba1c708137e0db890210628c

**Comment by eduardosan** [comment]
Recebido. Quando olhar eu te aviso.

Em 09-05-2016 19:49, Giovani Ferreira escreveu:

> @eduardosan https://github.com/eduardosan Tentei fazer o que vc 
> falou e dar uma compactada nas coisas. Nao sei se o resultado ficou 
> muito interessante nao, da uma avaliada ai. Adicionado no commit 
> 5814d68 
> https://github.com/giovanifss/Datacenter-Monitor/commit/5814d685d45064b4ba1c708137e0db890210628c
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> https://github.com/giovanifss/Datacenter-Monitor/issues/5#issuecomment-218012814

## 

Eduardo Santos
Programador

http://twitter.com/eduardosan
http://eduardosan.com

**Comment by giovanifss** [comment]
@eduardosan Novamente solicitando um feedback. Algumas coisas novas foram escritas, acho que ta tomando uma forma e corpo legais.

**Comment by giovanifss** [comment]
@eduardosan Tem mais novidade no artigo. O que eu te disse que era so a estrutura ta comencando a ganhar conteudo. To aguardando um feedback seu para talvez mudar alguma coisa.

**Comment by giovanifss** [comment]
Finished in 0ec2273d5633426a4a616cacb268ebc7e1ba4467 and 7ddbda0c1126312669896ec0c1a6d1f221d2af2f
